name: babyresell
services:
  - name: backend
    github:
      branch: main
      repo: yourusername/babyresell
    source_dir: backend
    http_port: 5000
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '5000'
      - key: MONGO_URI
        scope: RUN_TIME
        value: ${MONGO_URI}
      - key: JWT_SECRET
        scope: RUN_TIME
        value: ${JWT_SECRET}
      - key: JWT_EXPIRE
        value: '30d'
      - key: DO_SPACES_KEY
        scope: RUN_TIME
        value: ${DO_SPACES_KEY}
      - key: DO_SPACES_SECRET
        scope: RUN_TIME
        value: ${DO_SPACES_SECRET}
      - key: DO_SPACES_BUCKET
        value: ${DO_SPACES_BUCKET}
      - key: DO_SPACES_REGION
        value: ${DO_SPACES_REGION}
  
  - name: frontend
    github:
      branch: main
      repo: yourusername/babyresell
    source_dir: frontend
    build_command: npm run build
    run_command: npx serve -s build
    envs:
      - key: REACT_APP_API_URL
        value: ${APP_URL}/api

databases:
  - name: babyresell-db
    engine: mongodb
    cluster_name: babyresell-cluster
    production: true